#!/bin/bash

echo "=== Piano Track Reader Plugin - Logic Pro Testing Guide ==="
echo ""
echo "插件已成功安装到以下位置："
echo "• Audio Unit: ~/Library/Audio/Plug-Ins/Components/Piano Track Reader.component"
echo "• VST3: ~/Library/Audio/Plug-Ins/VST3/Piano Track Reader.vst3"
echo ""
echo "在 Logic Pro 中使用插件："
echo "1. 打开 Logic Pro"
echo "2. 创建新项目或打开现有项目"
echo "3. 在音轨上插入插件："
echo "   - 点击音轨的插件槽"
echo "   - 选择 Audio > Instrument > AU: Piano Track Reader"
echo "   - 或选择 Audio > MIDI FX > Piano Track Reader"
echo ""
echo "插件功能："
echo "• 点击 'Load MIDI File' 按钮选择 MIDI 文件"
echo "• 插件将分析文件并显示："
echo "  - 每个音轨的音符数量"
echo "  - 音符名称、开始时间和持续时间"
echo "  - 详细的时间信息"
echo ""
echo "测试文件："
echo "• 可以从网上下载标准 MIDI 文件进行测试"
echo "• 或在 Logic Pro 中导出 MIDI 文件测试"
echo ""
echo "插件已准备就绪！"